export enum ImportJobStatus {
  CREATED = 'CREATED',
  FILE_UPLOADED = 'FILE_UPLOADED',
  VALIDATED = 'VALIDATED',
  ANALYZED = 'ANALYZED',
  MAPPING_PENDING_APPROVAL = 'MAPPING_PENDING_APPROVAL',
  READY_TO_TRANSFORM = 'READY_TO_TRANSFORM',
  TRANSFORMED = 'TRANSFORMED',
  EXPORTED = 'EXPORTED',
  FAILED = 'FAILED',
}
